/* 
The useful classes for working with files in C++ are : under #include<fstream>
1. fstreambase
2. ofstream -> stream class to write on files -> drived from fstreambase 
3. ifstream -> stream class to read from files -> drived from fstreambase
4. fstream  -> stream class to both read and write from/to files....

There are two ways to open a file ....
1. using the constructor 
2. using the member function open() of the class 

1.  let see using the constructor .....

syntax for open and write it ...
ofstram object_name("filename.ext");
// now file is open for write it ....
// for writing to it ....
object_name<<.....;

syntax for open and read from it ....
ifstream object_name("filename.ext");
// now file is open for reading from it ....
// for reading from it ....
string st;
object_name>>st ;
// getline(object_name, st); 

syntax for open for writing and reading in the same program ...
fstream object_name("filename.ext");
// now this file is open for writing and reading ....   
// use   >>   and     <<    according to your requirement .....


2. opening the file using the member function open() of the class ..

//syntax ....

ofstream object_name ;
object_name.open("filename.ext"); 
otherthings ...similarly as above ......


// for closing the file ...use ...
object_name.close() ;

// getline(object_name , st); returns eof() when all the string of the file have been read and afterthat we are using getline() ...
// getline() --> read whole line as string ....

// When no files exist for writing -> if we are using ofstream for writing the files -> it will be created 
// automatically with the same name and extension that we are trying to open....

// if there is already exist a file and having its content ....then it will be overwritten if we write any content to it ...

*/